#!/usr/bin/env python3

import unicodedata
import sys
from pathlib import Path

RANGES = [
    (0x00A0, 0x02FF),
    (0x0300, 0x036F),
    (0x0370, 0x03FF),
    (0x0400, 0x052F),
    (0x0590, 0x05FF),
    (0x0600, 0x06FF),
    (0x0900, 0x097F),
    (0x1D00, 0x1DBF),
    (0x1E00, 0x1FFF),
    (0x2000, 0x209F),
    (0x20A0, 0x20CF),
    (0x2100, 0x214F),
    (0x2150, 0x218F),
    (0x2460, 0x24FF),
    (0x3000, 0x303F),
    (0x3040, 0x30FF),
    (0x3130, 0x318F),
    (0xFB00, 0xFB4F),
    (0xFB50, 0xFDFF),
    (0xFE30, 0xFE4F),
    (0xFE70, 0xFEFF),
    (0xFF00, 0xFFEF),
]


def main():
    nfkd_entries = []
    lower_entries = []

    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            ch = chr(cp)

            try:
                cat = unicodedata.category(ch)
            except Exception:
                continue
            if cat.startswith("C") and cat != "Cf":
                continue

            nfkd = unicodedata.normalize("NFKD", ch)
            if nfkd != ch:
                nfkd_entries.append((cp, [ord(c) for c in nfkd]))

            low = ch.lower()
            if low != ch:
                lower_entries.append((cp, [ord(c) for c in low]))




    ccc_entries = []
    for cp in range(0, 0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ccc = unicodedata.combining(chr(cp))
        if ccc != 0:
            ccc_entries.append((cp, ccc))


    nfkd_data = []
    nfkd_table = []
    for cp, decomp in nfkd_entries:
        off = len(nfkd_data)
        nfkd_data.extend(decomp)
        nfkd_table.append((cp, off, len(decomp)))

    lower_data = []
    lower_table = []
    for cp, low in lower_entries:
        off = len(lower_data)
        lower_data.extend(low)
        lower_table.append((cp, off, len(low)))

    def fmt_cp_array(name, data):
        lines = [f"static const uint32_t {name}[] = {{"]
        row = []
        for v in data:
            row.append(f"0x{v:05X}")
            if len(row) == 8:
                lines.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ", ".join(row) + ",")
        lines.append("};")
        return "\n".join(lines)

    def fmt_entry_array(name, entries):
        lines = [f"static const mtl_unicode_entry {name}[] = {{"]
        for cp, off, ln in entries:
            lines.append(f"    {{0x{cp:05X}, {off}, {ln}}},")
        lines.append("};")
        return "\n".join(lines)

    def fmt_ccc_array(name, entries):
        lines = [f"static const mtl_ccc_entry {name}[] = {{"]
        for cp, ccc in entries:
            lines.append(f"    {{0x{cp:05X}, {ccc}}},")
        lines.append("};")
        return "\n".join(lines)

    out_lines = [
        "// Generated by scripts/gen-nfkd-table.py. Do not edit.",
        "// Covers NFKD decomposition, lowercase mapping, and canonical",
        "// combining classes for tier-1 languages.",
        "// Hangul syllables (U+AC00..U+D7A3) are decomposed algorithmically.",
        "",
        "struct mtl_unicode_entry {",
        "    uint32_t cp;",
        "    uint32_t offset;",
        "    uint32_t length;",
        "};",
        "",
        "struct mtl_ccc_entry {",
        "    uint32_t cp;",
        "    uint8_t  ccc;",
        "};",
        "",
        fmt_cp_array("k_mtl_nfkd_data", nfkd_data),
        "",
        fmt_entry_array("k_mtl_nfkd_table", nfkd_table),
        "",
        fmt_cp_array("k_mtl_lower_data", lower_data),
        "",
        fmt_entry_array("k_mtl_lower_table", lower_table),
        "",
        fmt_ccc_array("k_mtl_ccc_table", ccc_entries),
        "",
        f"static const size_t k_mtl_nfkd_table_len = {len(nfkd_table)};",
        f"static const size_t k_mtl_lower_table_len = {len(lower_table)};",
        f"static const size_t k_mtl_ccc_table_len   = {len(ccc_entries)};",
        "",
    ]
    text = "\n".join(out_lines)
    out = Path(__file__).resolve().parent.parent / "src" / "mtl_unicode_tables.inc"
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out} ({len(nfkd_table)} nfkd, {len(lower_table)} lower, "
          f"{len(ccc_entries)} ccc)")


if __name__ == "__main__":
    sys.exit(main())
